
on:
  pull_request:
    branches:
      - main


jobs:
  clear-readme:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: Clear Readme
        run: echo -e "$(date +'%Y-%m-%d-%H-%M-%S') \n" > README.md
      - name: config git
        run: |
           git config --global user.email "action@github.com"
           git config --global user.name "GitHub Actions"

      - name: Commit readme
        run: |
          git fetch
          git checkout main
          git commit -am "Cleared readme" --author="GitHub Action <action@github.com>"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  run-tests:
    needs: clear-readme
    runs-on : ${{matrix.os}}

    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.9', '3.10', '3.11']
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: Install python
        uses: actions/setup-python@v3
        with:
          python-version: ${{matrix.python-version}}

      - name: Install pytest
        run: |
          pip install -U pytest


      # runs the test and puts the output in a temporary file that will not be tracked by git
      - name: Run pytest
        env:
          temp_log: temp_log.txt
        run : pytest


      - name: config git
        if: success() || failure()
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Actions"

      - name: Update readme with results
        if: success() || failure()
        run: |
          git fetch
          git checkout main
          echo -e "Test Status: ${{ job.status }} \n OS: ${{matrix.os}} and python version: ${{matrix.python-version}} \n" >> README.md
          git commit -am "Update test status on README " --author="GitHub Action <action@github.com>"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
