name: Automated Testing

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Pytest
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11']

    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: Install python
        uses: actions/setup-python@v3
        with:
          python-version: ${{matrix.python-version}}

      - name: Install pytest
        run: |
          pip install -U pytest

      - name: Run Pytest
        run: |
          pytest --junitxml=pytest_report.xml -q

      - name: Save test results
        if: always()
        id: test-results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: pytest_report.xml

  update-readme:
    name: Update README with test status
    needs: test
    if: always()
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Download test results
        uses: actions/download-artifact@v2
        with:
          name: test-results
          path: /home/runner/work/UnitTestingExercise/UnitTestingExercise/test-results


      - name: config git
        if: always()
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Actions"

      - name: Update README
        run: |
          echo -e "$(date +'%Y-%m-%d-%H-%M-%S') \n" > README.md
          echo "" >> README.md
          echo -e "![Tests](https://github.com/xRevx/UnitTestingExercise/actions/workflows/main.yml/badge.svg) \n" >> README.md   
          echo "## Test Results" >> README.md
          cat test-results/pytest_report.xml >> README.md

      - name: Set cache-control headers
        run: |
          echo "Cache-Control: no-store" >> .github/.htaccess
          

      - name: Commit changes
        run: |
          git commit -am "Update test status on README " --author="GitHub Action <action@github.com>"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}