on:
  pull_request:

jobs:
  run-tests:
    outputs:
      int_result: ${{ job.steps.run-tests.outputs.int_result }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version:
          - "3.9"
          - "3.10"
          - "3.11"

    name: python test
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install pytest
        run: pip install -U pytest

      # runs the test and puts the output in a temporary file that will not be tracked by git
      - name: Run pytest
        run: pytest -q > temp_status.txt

      - name: assign_result_fail
        if: failure()
        run:
          echo "::set-env name=int_result::-1"

      - name: assign_result_success
        if: success() && env.int_result == '0'
        run:
          echo "::set-env name=int_result::1"

      - name: add failure to status
        if: failure()
        run: |
          if [ "${{ matrix.os }}" = "windows" ]; then
            echo "${{ matrix.os }}_${{ matrix.python-version }}: failed" >> temp_log.txt
          else
            echo "${{ matrix.os }}_${{ matrix.python-version }}: failed" >> temp_log.txt
          fi

      - name: Print status
        run: echo '$temp_status.txt'

  add-status:
    runs-on: ubuntu-latest
    needs: run-tests

    steps:
      - name: add test fail badge
        if: env.int_result == '-1'
        run: echo -e "\n## __results from $(date +'%Y-%m-%d')__ ${{ github.event.pull_request.head.ref }} -> ${{ github.event.pull_request.base.ref }} ![Static Badge](https://img.shields.io/badge/test-fail-red)\n" >> status_log.txt

      # add pass badge if the test didn't fail
      - name: add test pass badge
        if: env.int_result == '1'
        run: echo -e "\n## __results from $(date +'%Y-%m-%d')__ ${{ github.event.pull_request.head.ref }} -> ${{ github.event.pull_request.base.ref }} ![Static Badge](https://img.shields.io/badge/test-pass-green)\n" >> status_log.txt

      - name: config git
        if: env.int_result == '1' || env.int_result == '-1'
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Actions"

      # the output log will be appended to the README.md in main, so a checkout is needed
      - name: checkout main
        if: env.int_result == '1' || env.int_result == '-1'
        run: |
          git fetch
          git checkout main

      - name: append log to README
        if: env.int_result == '1' || env.int_result == '-1'
        run: |
          cat status_log.txt > README.md
          cat temp_log.txt >> README.md

      - name: commit logs
        if: env.int_result == '1' || env.int_result == '-1'
        run: |
          git add README.md
          git commit -m "update README.md with results"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
