name: CI

on:
  pull_request:


jobs:
  run-tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version:
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"

    name: Test
    runs-on: ${{matrix.os}}
    env:
      log_Output: README.md
      temp_log: temp_log.txt

    steps:
      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: ${{matrix.python-version}}

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install pytest
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest

      - name: Run pytest
        run: pytest -q > $temp_log

      - name: add test fail badge
        if: failure()
        run: echo -e "\n## __results from $(date +'%Y-%m-%d')__ ${{ github.event.pull_request.head.ref }} -> ${{ github.event.pull_request.base.ref }} ![Static Badge](https://img.shields.io/badge/test-fail-red)\n" >> $log_Output

      - name: config git
        if: success() || failure()
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Actions"

      - name: checkout main
        if  : success() || failure()
        run : |
          git fetch
          git checkout main

      - name: append log to README
        if  : success() || failure()
        
        run : cat $temp_log >> $log_Output


      - name: commit logs
        if  : success() || failure()
        run : |
          git add $log_Output
          git commit -m "update $log_Output with results"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

