name: Automated Testing

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run Pytest
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.9, 3.10, 3.11]

    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Pytest
        run: pytest

      - name: Save test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: pytest_report.xml

  update-readme:
    name: Update README with test status
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Download test results
        uses: actions/download-artifact@v2
        with:
          name: test-results
          path: test-results

      - name: Update README
        run: |
          echo "<img alt=\"Tests\" src=\"https://github.com/xRevx/UnitTestingExercise/actions/workflows/main.yml/test-status.svg\">" >> README.md
          echo "" >> README.md
          echo "## Test Results" >> README.md
          

      - name: Commit changes
        run: |
          git config --global user.name "Your Name"
          git config --global user.email "your-email@example.com"
          git add README.md
          git commit -m "Update README with test status"
          git push