
on:
  pull_request:
    branches:
      - main


jobs:
  clear-readme:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: Clear Readme
        run: truncate -s 0 README.md

      - name: Commit readme
        run: |
          export GIT_AUTHOR_NAME="GitHub Action"
          export GIT_AUTHOR_EMAIL="action@github.com"
          git checkout ${{ github.head_ref }}
          git add README.md
          git commit -m "Cleared readme" --author="GitHub Action <action@github.com>"
          git push

  run-tests:
    needs: clear-readme
    runs-on : ${{matrix.os}}
    strategy:

      matrix:
        os: [ubuntu-latest, windows-latest]
        python-versions: ['3.9','3.10','3.11']
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: Install python
        uses: actions/setup-python@v3
        with:
          python-version: ${{matrix.python-version}}

      - name: Install pytest
        run: |
          python -m pip install --upgrade pip
          pip install -U pytest


      # runs the test and puts the output in a temporary file that will not be tracked by git
#      - name: Change working directory
#        run: cd /home/runner/work/UnitTestingExercise

      - name: Run pytest
        run : pytest -q

      - name: Update readme with results
        run: |
          echo "Test Status: ${{ job.status }}" >> README.md
          export GIT_AUTHOR_NAME="GitHub Action"
          export GIT_AUTHOR_EMAIL="action@github.com"
          git checkout ${{ github.head_ref }}
          git add README.md
          git commit -m "Update test status on README" --author="GitHub Action <action@github.com>"
          git push
